utils::globalVariables(c("OU2name", "ou5name", "ou5uid", "datim_uid",
                         "old_ou5code", "period", "DSD_TA", "names_prep_new",
                         "names_prep_ct", "names_hts_tst", "names_tx_new", "names_pmtct_eid",
                         "names_pmtct_hei_pos", "names_tx_curr", "names_tx_rtt", "names_tx_ml",
                         "names_pmtct_art", "names_tb_art", "names_tx_pvls", "names_tb_stat_d",
                         "names_tb_stat_n", "names_tx_tb_d", "names_tx_tb_n", "names_tb_prev",
                         "names_prep_new_kp", "names_prep_ct_kp", "names_hts_tst_kp",
                         "names_tx_new_kp", "names_tx_curr_kp", "names_tx_ml_kp", "names_tx_pvls_kp",
                         "names_arvdisp", "Total", "Code", "Test Result/Outcome/Duration", "Result",
                         "CoarseAgeGroup", "Sex", "District", "Province","SubDistrict", "Facility",
                         "code_num", "mfl_new_df", "OU5name", "Old_OU5Code", "df_fac", "indicator",
                         "usaid_facility", "numeratordenom", "agency", "code", "mech_name",
                         "mechanism", "ou", "partner", "uid", "facilityuid", "fiscal_year",
                         "funding_agency", "mech_code","mech_uid", "msd_folder", "n", "operatingunit",
                         "prime_partner_name", "reference_folder", "sitename", "dataElement",
                         "mech_df", "ndoh_clean", "ndoh_clean_kp", ".", "curr_qtr", "ndoh_filepath",
                         "dataElement_uid", "dsd_ta", "fiscal_quarter", "misaligned_sites", "new_ou5_code",
                         "names_tx_tb_d_pos", "names_tx_tb_d_testtype", "mech_mfl"
                         ))
